name: Pytest

on:
  push:
     branches:
      - "master"
  pull_request:
     branches:
      - "master"
      
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt install pytest
      
                
      - name: Unit test
        run: 
          python -m pytest backend/test/unit/test_usercontroller.py
           

